### ISSUE TITLE
Dark background for currently-loading pages

### ISSUE THREAD

**Issue by davidebaldini** [TigerKid001/Owl#2]
The add-on darkens the page only after it has fully loaded, leaving the default white background for a few seconds during loading. This results in a "white flash" whenever the user open a new page.

My suggestion is to apply a temporary dark background to the page while it loads or, if performances don't slow down, activate the content-script as soon as the page starts loading.

**Comment by TigerKid001** [comment]
Thanks for reporting this. It seems that the issue is with way stylesheets are attached when using the `attach` method of `content/mod`. Apparently, the attach method applies styles only after the page has been loaded, thus causing the white flashes when navigating. One way to solve this could be if the stylesheet is injected into the <head> of the page from the content-script. I'll try this out and also ask around on the IRCs if this functionality is intentional and if it can be controlled.

**Comment by TigerKid001** [comment]
Fixed in d710662

**Comment by davidebaldini** [comment]
Great.

Just a hint: I checked d710662 and found long inline quotes. For my add-on, I had troubles getting such quotes approved by AMO. In my case the quoted text was just static html.

**Comment by TigerKid001** [comment]
Thanks for the heads up. I too wasn't sure if AMO would approve them, but I didn't want to use any file ops nor minify the css into one line (because they'll definitely point out that one), so went with this. Plus, it's just basic CSS so I guess it won't be a trouble to anyone.

**Comment by PiQuer** [comment]
Hi, I am using version 1.3.1 which should contain d710662, but I still see the white flashes when loading pages, i.e. exactly the symptoms @davidebaldini reported originally. What could be the cause?

**Comment by TigerKid001** [comment]
Hi, changes in d701662 try to minimize the white flashes (by injecting styles as soon as they can be injected) but have not yet been completely removed. So, white flashes will still remain on some websites, especially the ones that require longer time to parse.

**Comment by PiQuer** [comment]
Thanks for the explanation.

**Comment by davidebaldini** [comment]
I noticed that an add-on similar to Owl named [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/) does darken the pages without any initial white flash during loading. Perhaps it configures some FF color setting beside injecting a CSS?
